import {
  AccountBalance,
  Description,
  Equalizer,
  Group,
  LocalMall,
  ShoppingCart,
  SpeedOutlined,
  Style,
} from '@mui/icons-material';

import { ROUTES } from '@/routes/routes';
import { INavigationGroup } from '@/types/navigations';

// export const NAVIGATIONS: INavigationItem[] = [
//   // {
//   //   title: 'Dashboard',
//   //   icon: <Window />,
//   //   isChildren: false,
//   //   path: '/dashboard',
//   // },
//   {
//     title: 'Quản lý người dùng',
//     icon: <AccountCircle />,
//     isChildren: false,
//     path: '/users',
//     code: PERMISSIONS_ENUM.USERS,
//   },
//   // {
//   //   title: 'Quản lý trang chủ',
//   //   icon: <Home />,
//   //   isChildren: true,
//   //   path: '/homepage',
//   //   code: PERMISSIONS_ENUM.HOMEPAGE,
//   //   children: [
//   //     {
//   //       title: 'Banner',
//   //       icon: '',
//   //       isChildren: false,
//   //       path: '/homepage/banners',
//   //       level: 1,
//   //     },
//   //     {
//   //       title: 'Thông báo',
//   //       icon: '',
//   //       isChildren: false,
//   //       path: '/homepage/notifications',
//   //       level: 1,
//   //     },
//   //     {
//   //       title: 'Sự kiện trong tháng',
//   //       icon: '',
//   //       isChildren: false,
//   //       path: '/homepage/events',
//   //       level: 1,
//   //     },
//   //     {
//   //       title: 'Liên kết',
//   //       icon: '',
//   //       isChildren: false,
//   //       path: '/homepage/links',
//   //       level: 1,
//   //     },
//   //   ],
//   // },
//   {
//     title: 'Quản lý thông tin',
//     icon: <Feed />,
//     isChildren: true,
//     path: '/information',
//     code: PERMISSIONS_ENUM.INFORMATION,
//     children: [
//       {
//         title: 'Khoa và bộ môn',
//         icon: '',
//         isChildren: false,
//         path: '/information/departments',
//         level: 1,
//       },
//       // {
//       //   title: 'Khoa và bộ môn',
//       //   icon: '',
//       //   isChildren: true,
//       //   path: '/information/section',
//       //   level: 1,
//       //   children: [
//       //     {
//       //       title: 'Nhóm khoa',
//       //       icon: '',
//       //       isChildren: false,
//       //       path: '/information/section-groups',
//       //       level: 2,
//       //     },
//       //     {
//       //       title: 'Khoa',
//       //       icon: '',
//       //       isChildren: false,
//       //       path: '/information/sections',
//       //       level: 2,
//       //     },
//       //   ],
//       // },
//       {
//         title: 'Phòng ban chức năng',
//         icon: '',
//         isChildren: false,
//         path: '/information/functions',
//         level: 1,
//       },
//       {
//         title: 'Trung tâm và Viện',
//         icon: '',
//         isChildren: false,
//         path: '/information/institutes',
//         level: 1,
//       },
//       {
//         title: 'Đoàn thể',
//         icon: '',
//         isChildren: false,
//         path: '/information/parties',
//         level: 1,
//       },
//       {
//         title: 'Đảng Ủy Trường',
//         icon: '',
//         isChildren: false,
//         path: '/information/school-party-committee',
//         level: 1,
//       },
//     ],
//   },
//   {
//     title: 'Quản lý Menu',
//     icon: <Menu />,
//     isChildren: true,
//     path: '/menu',
//     code: PERMISSIONS_ENUM.MENU,
//     children: [
//       // {
//       //   title: 'Trang',
//       //   icon: '',
//       //   isChildren: false,
//       //   path: '/menu/pages',
//       //   level: 1,
//       // },
//       {
//         title: 'Menu',
//         icon: '',
//         isChildren: false,
//         path: '/menu/menus',
//         level: 1,
//       },
//       {
//         title: 'Danh mục',
//         icon: '',
//         isChildren: false,
//         path: '/menu/folders',
//         level: 1,
//       },
//       {
//         title: 'Blog',
//         icon: '',
//         isChildren: false,
//         path: '/menu/blogs',
//         level: 1,
//       },
//     ],
//   },
//   // {
//   //   title: 'Quản lý nội dung',
//   //   icon: <ContentPaste />,
//   //   isChildren: false,
//   //   path: '/posts',
//   //   code: PERMISSIONS_ENUM.POSTS,
//   // },
//   {
//     title: 'Lịch công tác',
//     icon: <DateRange />,
//     isChildren: false,
//     path: '/schedules',
//     code: PERMISSIONS_ENUM.SCHEDULES,
//   },
//   // {
//   //   title: 'Duyệt tin',
//   //   icon: <Newspaper />,
//   //   isChildren: false,
//   //   path: '/approve',
//   //   code: PERMISSIONS_ENUM.APPROVE,
//   // },
//   {
//     title: 'Quản lý nhân sự',
//     icon: <Portrait />,
//     isChildren: true,
//     path: '/staff',
//     code: PERMISSIONS_ENUM.STAFF,
//     children: [
//       {
//         title: 'Nhân sự',
//         icon: '',
//         isChildren: false,
//         path: '/staff/employees',
//         level: 1,
//       },
//       {
//         title: 'Chức vụ',
//         icon: '',
//         isChildren: false,
//         path: '/staff/positions',
//         level: 1,
//       },
//     ],
//   },
//   {
//     title: 'Footer',
//     icon: <Crop75 />,
//     isChildren: true,
//     path: '/footer',
//     code: PERMISSIONS_ENUM.FOOTER,
//     children: [
//       {
//         title: 'Footer Trái',
//         icon: '',
//         isChildren: false,
//         path: '/footer/left',
//         level: 1,
//       },
//       {
//         title: 'Footer Phải',
//         icon: '',
//         isChildren: true,
//         path: '/footer/right',
//         level: 1,
//         children: [
//           {
//             title: 'Danh mục cha',
//             icon: '',
//             isChildren: false,
//             path: ROUTES.FOOTER.RIGHT,
//             level: 2,
//           },
//           {
//             title: 'Danh mục con',
//             icon: '',
//             isChildren: false,
//             path: ROUTES.FOOTER.RIGHT_SUB,
//             level: 2,
//           },
//         ],
//       },
//       // {
//       //   title: 'Thông tin',
//       //   icon: '',
//       //   isChildren: false,
//       //   path: '/footer/content',
//       //   level: 1,
//       // },
//     ],
//   },
//   // {
//   //   title: 'Ngôn ngữ',
//   //   icon: <Language />,
//   //   isChildren: false,
//   //   path: '/languages',
//   //   code: PERMISSIONS_ENUM.LANGUAGE,
//   // },
// ];

export const NAVIGATIONS: INavigationGroup[] = [
  {
    id: '1',
    name: 'Overview',
    children: [
      {
        id: '1',
        name: 'App',
        icon: <SpeedOutlined />,
        href: ROUTES.OVERVIEW.HOME,
        children: [],
      },
      {
        id: '2',
        name: 'E-Commerce',
        icon: <LocalMall />,
        href: ROUTES.OVERVIEW.E_COMMERCE,
        children: [],
      },
      {
        id: '3',
        name: 'Analytics',
        icon: <Equalizer />,
        href: ROUTES.OVERVIEW.ANALYTICS,
        children: [],
      },
      {
        id: '4',
        name: 'Banking',
        icon: <AccountBalance />,
        href: ROUTES.OVERVIEW.BANKING,
        children: [],
      },
      {
        id: '5',
        name: 'Booking',
        icon: <Style />,
        href: ROUTES.OVERVIEW.BOOKING,
        children: [],
      },
      {
        id: '6',
        name: 'File',
        icon: <Description />,
        href: ROUTES.OVERVIEW.FILE,
        children: [],
      },
    ],
  },
  {
    id: '2',
    name: 'Management',
    children: [
      {
        id: '1',
        name: 'User',
        icon: <Group />,
        href: ROUTES.MANAGEMENT.USER.ROOT,
        children: [
          { id: '1', name: 'Profile', href: ROUTES.MANAGEMENT.USER.PROFILE },
          { id: '2', name: 'Cards', href: ROUTES.MANAGEMENT.USER.CARDS },
          { id: '3', name: 'List', href: ROUTES.MANAGEMENT.USER.LIST },
          { id: '4', name: 'Create', href: ROUTES.MANAGEMENT.USER.CREATE },
        ],
      },
      {
        id: '2',
        name: 'Product',
        icon: <ShoppingCart />,
        href: ROUTES.MANAGEMENT.PRODUCT.ROOT,
        children: [
          { id: '1', name: 'List', href: ROUTES.MANAGEMENT.PRODUCT.LIST },
          { id: '2', name: 'Details', href: ROUTES.MANAGEMENT.PRODUCT.DETAILS },
          { id: '3', name: 'Create', href: ROUTES.MANAGEMENT.PRODUCT.CREATE },
          { id: '4', name: 'Edit', href: ROUTES.MANAGEMENT.PRODUCT.EDIT },
        ],
      },
    ],
  },
];
