export * from './MActiveForm';
export * from './MIntroduceForm';
export * from './MLeadershipForm';
export * from './MLecturerQualityForm';
export * from './MOrganizationalStructureForm';
export * from './MSubjectForm';
export * from './MTimelineForm';
export * from './MTrainingGoalForm';
export * from './MTrainingSectorForm';
